# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "ubungtu"
  config.vm.network "private_network", ip: "192.168.111.110"
  config.vm.synced_folder ".", "/vagrant", disable: true
  config.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
      vb.memory = 2048
  end
  # config.vm.provision "shell", inline: $script
end

